// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gigwskujftrqvvulfayl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdpZ3dza3VqZnRycXZ2dWxmYXlsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY4MzU1ODEsImV4cCI6MjA2MjQxMTU4MX0.TyIJexHoZNmsnPJcOmxpfHI0gerOxC6NMqKQWTv4ghA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Criar cliente com configuração para persistir a sessão
export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      autoRefreshToken: true,
      persistSession: true,
      storageKey: 'supabase_auth_token',
      storage: localStorage
    }
  }
);
